name: job_search_oficial
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.6.7
  flutter_lints: ^5.0.0
  google_fonts: ^6.1.0
  page_transition: ^2.1.0
  flutter_animate: ^4.5.2
  shared_preferences: ^2.3.5
  bloc: ^9.0.0
  firebase_auth: ^5.5.4
  equatable: ^2.0.7
  firebase_core: ^3.13.1
  flutter_bloc: ^9.1.1
  image_picker: ^1.1.2
  flutter_svg: ^2.0.7
  lottie: ^3.3.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/icons/
    - assets/svg/
    - assets/lottie/