// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn3c3hRBomZN69H2o_C5k6E64AU3NSoys',
    appId: '1:933821328299:web:a699343024bf6e087800ee',
    messagingSenderId: '933821328299',
    projectId: 'oficiales-c07ad',
    authDomain: 'oficiales-c07ad.firebaseapp.com',
    storageBucket: 'oficiales-c07ad.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_jr33-h9_oit7N1O5dnO39AngsZXSLBw',
    appId: '1:933821328299:android:b6124995b8e7531d7800ee',
    messagingSenderId: '933821328299',
    projectId: 'oficiales-c07ad',
    storageBucket: 'oficiales-c07ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4fM_iodxnkERo3iLzwkMjM_CYtl4HCtI',
    appId: '1:933821328299:ios:42958af902f313437800ee',
    messagingSenderId: '933821328299',
    projectId: 'oficiales-c07ad',
    storageBucket: 'oficiales-c07ad.firebasestorage.app',
    iosBundleId: 'com.example.jobSearchOficial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4fM_iodxnkERo3iLzwkMjM_CYtl4HCtI',
    appId: '1:933821328299:ios:42958af902f313437800ee',
    messagingSenderId: '933821328299',
    projectId: 'oficiales-c07ad',
    storageBucket: 'oficiales-c07ad.firebasestorage.app',
    iosBundleId: 'com.example.jobSearchOficial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAn3c3hRBomZN69H2o_C5k6E64AU3NSoys',
    appId: '1:933821328299:web:5bd7523d7081b0cb7800ee',
    messagingSenderId: '933821328299',
    projectId: 'oficiales-c07ad',
    authDomain: 'oficiales-c07ad.firebaseapp.com',
    storageBucket: 'oficiales-c07ad.firebasestorage.app',
  );
}
